## Component Visualization Report 

+ Generated with R package icreport

```{r global_options, include=FALSE}
# setting global options 
figure.outpath <- paste(output_path,"/icreport_figures/",prefix,"/",sep="")
opts_chunk$set(fig.path=figure.outpath,dev=file.ext, warning=FALSE, message=FALSE)
options(warn=-1,width = 100)
flower.palette <- c("#283545","#E09E12","#A72613","#95CDDC","#395717","#3A3B35","#D68931","#442243")
```

```{r, echo = FALSE, comment = ""}

cat(toupper(attr(input_list, "method")), " Analysis Report \n")
cat("Dataset = ", prefix,"\n")

```

### Summary Information

```{r Summary, echo = FALSE, comment="", warnings = FALSE, fig.width = 12, fig.height = 4}

# need to work on summary 

summary_plots = plot_summary(input_list)

```



### Individual Component Information

```{r comp_plots, echo = FALSE, comment="", warning=FALSE, fig.width = 10, fig.height = 6}

for( i in 1:n_comps){
    ###################### Plotting without Gene information ########################## 
    # check if there is a specified order for the ICs (default is by explained variance)
    p <- order(input_list$percent_var, decreasing = TRUE)[i]
    
    
    cat("------------------------------------------------------------------------------","\n")

    cat(paste0("plot#",i),"-", paste0("Comp",p),"\n")
    cat("Variance Percent = ", input_list$percent_var[p], "\n\n")

    if(attr(input_list, "covar_cor") == "yes"){
        cat("-- Component covariate correlations\n")
        print(input_list$comp_cov[[p]])
    }

    cat("------------------------------------------------------------------------------","\n")
    
    single_plot = plot_component(input_list, comp_idx = p, geneinfo_df = geneinfo_df)
    

    
}

```


